# Generated by Django 3.0.7 on 2020-07-01 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0003_leasing'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Leasing',
        ),
    ]
