# Generated by Django 3.0.7 on 2020-07-01 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0005_leasing'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Leasing',
            new_name='Lease',
        ),
    ]
