# Generated by Django 3.0.7 on 2020-07-09 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0007_auto_20200701_2259'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Leasing',
        ),
    ]
