# Generated by Django 3.0.7 on 2020-06-25 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carrier',
            old_name='carrier',
            new_name='name',
        ),
    ]
