# Generated by Django 3.0.7 on 2020-06-25 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_auto_20200625_0350'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='contract_end',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='contract_start',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='user_num',
            field=models.IntegerField(null=True),
        ),
    ]
