# Generated by Django 3.0.7 on 2020-06-25 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0006_auto_20200625_0620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='contract_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='contract_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='contract_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='invoice.ContractType'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user_num',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
