# Generated by Django 3.0.7 on 2020-06-25 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0010_auto_20200625_0717'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='user',
            new_name='creator',
        ),
        migrations.AddField(
            model_name='invoice',
            name='end_user',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
