# Generated by Django 3.0.7 on 2020-06-25 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0011_auto_20200625_0802'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='remark',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
