# Generated by Django 3.0.7 on 2020-06-26 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0012_order_remark'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='create_date',
            new_name='invoice_date',
        ),
    ]
