# Generated by Django 3.0.7 on 2020-06-26 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0013_auto_20200626_0642'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_id',
            new_name='id',
        ),
    ]
