# Generated by Django 3.0.7 on 2020-07-01 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0016_order_serial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='serial',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
